### ISSUE TITLE
style

### ISSUE THREAD

**Issue by asukasouryu** [SkyZH/raytracer.rs#3]
I used your code. That is amazing. But it seems to only produce a dark-looking picture. How do I make it produce a brightly styled picture?

**Comment by SkyZH** [comment]
Hi asukasouryu,

There are two ways to do this.

The first method is to change https://github.com/SkyZH/raytracer.rs/blob/master/src/tracer/world.rs , where there are some code commented. By uncommenting these lines and delete `Vec3::new(0.0, 0.0, 0.0)`, you can make the sky bright.

Another way is to build a big light. Uncomment the lines in https://github.com/SkyZH/raytracer.rs/blob/master/src/main.rs , and there'll be a big light above the spheres.

**Comment by asukasouryu** [comment]
Thanks for your answer. Another problem, why run code will lead to cpu usage higher and fan turn the loud?

**Comment by SkyZH** [comment]
Refer to the render config `let renderer = ThreadRenderer::new::<MainRenderProvider>(1600, 800, 256, 8, 16, 8);`
Rendering every pixel requires simulating 256 rays, and every ray will bounce at most 50 times (configured in `world.rs`).
And now there're 1600x800 pixels, rendered in 8 workers. 
Therefore it requires `1600*800*256*50 = 16384000000` calculations at most to render an image. This is a very cpu-intense operation.
