### ISSUE TITLE
What are the new features?

### ISSUE THREAD

**Issue by Najilia** [skyzh/raytracer.rs#5]
This looks great and I ran the new version and legacy version of ray tracer, this version of the deployment is significantly faster, so what is the difference between the two?

**Comment by SkyZH** [comment]
This version is still working in progress, some features (camera, texture, light, threaded rendering, etc.) haven't been done. And objects in scene (4 spheres) aren't as many as the legacy version (100+ spheres).

I upgraded to Rust 2018 while employing some new features, thereby reducing memory-related overhead. And I switched all vectors from `f64` to `f32`, which may contribute to better performance. I'll make some benchmarks after I finsh writing this version.

**Comment by SkyZH** [comment]
Meanwhile I'm working on implementing on other books in "Ray Tracing in One Weekend" series and introducing new features such as object hierarchy and motion blur.

**Comment by Najilia** [comment]
> Meanwhile I'm working on implementing other chapters and books in "Ray Tracing in One Weekend" series and introducing new features such as object hierarchy and motion blur.

THX✓ I'll keep track of your raytracer project.

**Comment by Najilia** [comment]
When I run the compiled binary file in '/target/release ', the program does not prompt, except for 100% CPU usage. BTW, I typed ‘ cargo run --release’ in cmd.

**Comment by SkyZH** [comment]
Refer to the README, in this new version you should run this command to enable logging (if you're using bash)

```
RUST_LOG="raytracer=info" cargo run --release
```

**Comment by Najilia** [comment]
> Refer to the README, in this new version you should run this command to enable logging (if you're using bash)
> 
> ```
> RUST_LOG="raytracer=info" cargo run --release
> ```

I run this command in Powershell, but `RUST_LOG=raytracer=info` cannot be recognized.

**Comment by SkyZH** [comment]
Are you using Windows?

In cmd,
```
set RUST_LOG=raytracer=info & cargo run --release 
```

In Powershell,
```
$env:RUST_LOG='raytracer=info';cargo run --release 
```

**Comment by SkyZH** [comment]
If succeed, you may see information like this:

![image](https://user-images.githubusercontent.com/4198311/51116265-97cb3d80-1845-11e9-953e-24e725e86f2e.png)

**Comment by SkyZH** [comment]
I've made a new commit, the latest version should automatically output render info without setting `RUST_LOG`.
